spring:
    datasource:
        url: 'jdbc:h2:mem:testdb'
        initialization-mode: always
    h2:
        console:
            enabled: true
            path: /h2
 
server: 
  port: 8080
  servlet:
    context-path: /sql2csv
    
logging:
  level:
    org.springframework: INFO
    csv: INFO
    org.apache.camel: INFO